

"""
This is a text file outlining the criteria and logic used for various parts of the project

Part 3: Finding relevant videos

Criteria for inclusion:
    Relevance:
        Channel found via the search method(s)
            1. Search by keywords on YouTube - using #notfinancialadvice, crypto to buy, stocks to buy, what to invest in
            2. Snowball method from Google search of most important investing influencers on YouTube
        Video itself covers investing (any product)
        Video or channel over X views (X TO BE DECIDED ON VIEWING THE LIST OF VIDEOS)

    Pragmatics - must meet the following criteria:
        Transcript available on YouTube
        Between 2 - 10-minute videos (may also do shorts if possible)


Part 4: Webscraping

What data to include:
    Channel
    Date
    Title
    Description
    Video length
    Number of likes & dislikes
    Number of comments

    Transcript text
        Autogenerated / Creator written

"""