
"""
This script is for the Webscraping section of the 'Analysis of Investing on YouTube' project.
"""

# Running the script which loads the packages for the project
import subprocess
import sys

python_executable = sys.executable
subprocess.call([python_executable, "Installing & Loading packages.py"])

""" Part 1: Connecting to YouTube API """








""" Part 2: Finding relevant videos """

"""
Criteria for inclusion:
    Relevance:
        Channel found via the search method(s)
            1. Search by keywords on YouTube - using #notfinancialadvice, crypto to buy, stocks to buy, what to invest in 
            2. Snowball method from Google search of most important investing influencers on YouTube
        Video itself covers investing (any product)
        Video or channel over X views (X TO BE DECIDED ON VIEWING THE LIST OF VIDEOS)
    
    Pragmatics - must meet the following criteria:
        Transcript available on YouTube
        Between 2 - 10 minute videos (may also do shorts if possible)
"""





""" Part 3: Scraping the data """

"""
What data to include? 
    Channel
    Date
    Title
    Description
    Video length
    Number of likes & dislikes
    Number of comments
    
    Transcript text
        Autogenerated / Creator written
"""



""" Part 4: Creating the dataset """

